INSERT INTO pokemon_proyects.pokemon (pokemon_name, tipo_1, tipo_2, habilidades)
VALUES ('Caterpie','Bug','','[ RunAway - ShieldDust ]'),
('Metapod','Bug','','[ ShedSkin ]'),
('Butterfree','Bug','Flying','[ TintedLens ]'),
('Weedle','Bug','Poison','[ RunAway - ShieldDust ]'),
('Kakuna','Bug','Poison','[ ShedSkin ]'),
('Beedrill','Bug','Poison','[ Sniper - Swarm ]'),
('Pidgey','Normal','Flying','[ BigPecks - KeenEye - TangledFeet ]'),
('Pidgeotto','Normal','Flying','[ BigPecks - KeenEye - TangledFeet ]'),
('Pidgeot','Normal','Flying','[ BigPecks - KeenEye - TangledFeet ]'),
('Rattata','Normal','','[ Guts - Hustle - RunAway ]'),
('Raticate','Normal','','[ Guts - Hustle - RunAway ]'),
('Spearow','Normal','Flying','[ KeenEye - Sniper ]'),
('Fearow','Normal','Flying','[ KeenEye - Sniper ]'),
('Ekans','Poison','','[ Intimidate - ShedSkin - Unnerve ]'),
('Arbok','Poison','','[ Intimidate - ShedSkin - Unnerve ]'),
('Pikachu','Electric','','[ LightningRod - Static ]'),
('Raichu','Electric','','[ LightningRod - Static ]'),
('Sandshrew','Ground','','[ SandRush - SandVeil ]'),
('Sandslash','Ground','','[ SandRush - SandVeil ]'),
('Nidoranâ™€','Poison','','[ Hustle - PoisonPoint - Rivalry ]'),
('Nidorina','Poison','','[ Hustle - PoisonPoint - Rivalry ]'),
('Nidoqueen','Poison','Ground','[ PoisonPoint - Rivalry - SheerForce ]'),
('Nidoranâ™‚','Poison','','[ Hustle - PoisonPoint - Rivalry ]'),
('Nidorino','Poison','','[ Hustle - PoisonPoint - Rivalry ]'),
('Nidoking','Poison','Ground','[ PoisonPoint - Rivalry - SheerForce ]'),
('Clefairy','Fairy','','[ CuteCharm - FriendGuard - MagicGuard ]'),
('Clefable','Fairy','','[ CuteCharm - MagicGuard - Unaware ]'),
('Vulpix','Fire','','[ Drought - FlashFire ]'),
('Ninetales','Fire','','[ Drought - FlashFire ]'),
('Jigglypuff','Normal','Fairy','[ Competitive - CuteCharm - FriendGuard ]'),
('Wigglytuff','Normal','Fairy','[ Competitive - CuteCharm - Frisk ]'),
('Zubat','Poison','Flying','[ Infiltrator - InnerFocus ]'),
('Golbat','Poison','Flying','[ Infiltrator - InnerFocus ]'),
('Oddish','Grass','Poison','[ Chlorophyll - RunAway ]'),
('Gloom','Grass','Poison','[ Chlorophyll - Stench ]'),
('Vileplume','Grass','Poison','[ Chlorophyll - EffectSpore ]'),
('Paras','Bug','Grass','[ Damp - DrySkin - EffectSpore ]'),
('Parasect','Bug','Grass','[ Damp - DrySkin - EffectSpore ]'),
('Venonat','Bug','Poison','[ RunAway - TintedLens ]'),
('Venomoth','Bug','Poison','[ ShieldDust - TintedLens - WonderSkin ]'),
('Diglett','Ground','','[ ArenaTrap - SandForce - SandVeil ]'),
('Dugtrio','Ground','','[ ArenaTrap - SandForce - SandVeil ]'),
('Meowth','Normal','','[ Pickup - Technician - Unnerve ]'),
('Persian','Normal','','[ Limber - Technician - Unnerve ]'),
('Psyduck','Water','','[ CloudNine - Damp - SwiftSwim ]'),
('Golduck','Water','','[ CloudNine - Damp - SwiftSwim ]'),
('Mankey','Fighting','','[ AngerPoint - Defiant - VitalSpirit ]'),
('Primeape','Fighting','','[ AngerPoint - Defiant - VitalSpirit ]'),
('Growlithe','Fire','','[ FlashFire - Intimidate - Justified ]'),
('Arcanine','Fire','','[ FlashFire - Intimidate - Justified ]'),
('Poliwag','Water','','[ Damp - SwiftSwim - WaterAbsorb ]'),
('Poliwhirl','Water','','[ Damp - SwiftSwim - WaterAbsorb ]'),
('Poliwrath','Water','Fighting','[ Damp - SwiftSwim - WaterAbsorb ]'),
('Abra','Psychic','','[ InnerFocus - MagicGuard - Synchronize ]'),
('Kadabra','Psychic','','[ InnerFocus - MagicGuard - Synchronize ]'),
('Alakazam','Psychic','','[ InnerFocus - MagicGuard - Synchronize ]'),
('Machop','Fighting','','[ Guts - NoGuard - Steadfast ]'),
('Machoke','Fighting','','[ Guts - NoGuard - Steadfast ]'),
('Machamp','Fighting','','[ Guts - NoGuard - Steadfast ]'),
('Bellsprout','Grass','Poison','[ Chlorophyll - Gluttony ]'),
('Weepinbell','Grass','Poison','[ Chlorophyll - Gluttony ]'),
('Victreebel','Grass','Poison','[ Chlorophyll - Gluttony ]'),
('Tentacool','Water','Poison','[ ClearBody - LiquidOoze - RainDish ]'),
('Tentacruel','Water','Poison','[ ClearBody - LiquidOoze - RainDish ]'),
('Geodude','Rock','Ground','[ RockHead - SandVeil - Sturdy ]'),
('Graveler','Rock','Ground','[ RockHead - SandVeil - Sturdy ]'),
('Golem','Rock','Ground','[ RockHead - SandVeil - Sturdy ]'),
('Ponyta','Fire','','[ FlameBody - FlashFire - RunAway ]'),
('Rapidash','Fire','','[ FlameBody - FlashFire - RunAway ]'),
('Slowpoke','Water','Psychic','[ Oblivious - OwnTempo - Regenerator ]'),
('Slowbro','Water','Psychic','[ Oblivious - OwnTempo - Regenerator ]'),
('Magnemite','Electric','Steel','[ Analytic - MagnetPull - Sturdy ]'),
('Magneton','Electric','Steel','[ Analytic - MagnetPull - Sturdy ]'),
('Farfetchd','Normal','Flying','[ Defiant - InnerFocus - KeenEye ]'),
('Doduo','Normal','Flying','[ EarlyBird - RunAway - TangledFeet ]'),
('Dodrio','Normal','Flying','[ EarlyBird - RunAway - TangledFeet ]'),
('Seel','Water','','[ Hydration - IceBody - ThickFat ]'),
('Dewgong','Water','Ice','[ Hydration - IceBody - ThickFat ]'),
('Grimer','Poison','','[ PoisonTouch - Stench - StickyHold ]'),
('Muk','Poison','','[ PoisonTouch - Stench - StickyHold ]'),
('Shellder','Water','','[ Overcoat - ShellArmor - SkillLink ]'),
('Cloyster','Water','Ice','[ Overcoat - ShellArmor - SkillLink ]'),
('Gastly','Ghost','Poison','[ Levitate ]'),
('Haunter','Ghost','Poison','[ Levitate ]'),
('Gengar','Ghost','Poison','[ CursedBody ]'),
('Onix','Rock','Ground','[ RockHead - Sturdy - WeakArmor ]'),
('Drowzee','Psychic','','[ Forewarn - InnerFocus - Insomnia ]'),
('Hypno','Psychic','','[ Forewarn - InnerFocus - Insomnia ]'),
('Krabby','Water','','[ HyperCutter - SheerForce - ShellArmor ]'),
('Kingler','Water','','[ HyperCutter - SheerForce - ShellArmor ]'),
('Voltorb','Electric','','[ Aftermath - Soundproof - Static ]'),
('Electrode','Electric','','[ Aftermath - Soundproof - Static ]'),
('Exeggcute','Grass','Psychic','[ Chlorophyll - Harvest ]'),
('Exeggutor','Grass','Psychic','[ Chlorophyll - Harvest ]'),
('Cubone','Ground','','[ BattleArmor - LightningRod - RockHead ]'),
('Marowak','Ground','','[ BattleArmor - LightningRod - RockHead ]'),
('Hitmonlee','Fighting','','[ Limber - Reckless - Unburden ]'),
('Hitmonchan','Fighting','','[ InnerFocus - IronFist - KeenEye ]'),
('Lickitung','Normal','','[ CloudNine - Oblivious - OwnTempo ]'),
('Koffing','Poison','','[ Levitate - NeutralizingGas - Stench ]'),
('Weezing','Poison','','[ Levitate - NeutralizingGas - Stench ]'),
('Rhyhorn','Ground','Rock','[ LightningRod - Reckless - RockHead ]'),
('Rhydon','Ground','Rock','[ LightningRod - Reckless - RockHead ]'),
('Chansey','Normal','','[ Healer - NaturalCure - SereneGrace ]'),
('Tangela','Grass','','[ Chlorophyll - LeafGuard - Regenerator ]'),
('Kangaskhan','Normal','','[ EarlyBird - InnerFocus - Scrappy ]'),
('Horsea','Water','','[ Damp - Sniper - SwiftSwim ]'),
('Seadra','Water','','[ Damp - PoisonPoint - Sniper ]'),
('Goldeen','Water','','[ LightningRod - SwiftSwim - WaterVeil ]'),
('Seaking','Water','','[ LightningRod - SwiftSwim - WaterVeil ]'),
('Staryu','Water','','[ Analytic - Illuminate - NaturalCure ]'),
('Starmie','Water','Psychic','[ Analytic - Illuminate - NaturalCure ]'),
('Mr. Mime','Psychic','Fairy','[ Filter - Soundproof - Technician ]'),
('Scyther','Bug','Flying','[ Steadfast - Swarm - Technician ]'),
('Jynx','Ice','Psychic','[ DrySkin - Forewarn - Oblivious ]'),
('Electabuzz','Electric','','[ Static - VitalSpirit ]'),
('Magmar','Fire','','[ FlameBody - VitalSpirit ]'),
('Pinsir','Bug','','[ HyperCutter - MoldBreaker - Moxie ]'),
('Tauros','Normal','','[ AngerPoint - Intimidate - SheerForce ]'),
('Magikarp','Water','','[ Rattled - SwiftSwim ]'),
('Gyarados','Water','Flying','[ Intimidate - Moxie ]'),
('Lapras','Water','Ice','[ Hydration - ShellArmor - WaterAbsorb ]'),
('Ditto','Normal','','[ Imposter - Limber ]'),
('Eevee','Normal','','[ Adaptability - Anticipation - RunAway ]'),
('Vaporeon','Water','','[ Hydration - WaterAbsorb ]'),
('Jolteon','Electric','','[ QuickFeet - VoltAbsorb ]'),
('Flareon','Fire','','[ FlashFire - Guts ]'),
('Porygon','Normal','','[ Analytic - Download - Trace ]'),
('Omanyte','Rock','Water','[ ShellArmor - SwiftSwim - WeakArmor ]'),
('Omastar','Rock','Water','[ ShellArmor - SwiftSwim - WeakArmor ]'),
('Kabuto','Rock','Water','[ BattleArmor - SwiftSwim - WeakArmor ]'),
('Kabutops','Rock','Water','[ BattleArmor - SwiftSwim - WeakArmor ]'),
('Aerodactyl','Rock','Flying','[ Pressure - RockHead - Unnerve ]'),
('Snorlax','Normal','','[ Gluttony - Immunity - ThickFat ]'),
('Articuno','Ice','Flying','[ Pressure - SnowCloak ]'),
('Zapdos','Electric','Flying','[ Pressure - Static ]'),
('Moltres','Fire','Flying','[ FlameBody - Pressure ]'),
('Dratini','Dragon','','[ MarvelScale - ShedSkin ]'),
('Dragonair','Dragon','','[ MarvelScale - ShedSkin ]'),
('Dragonite','Dragon','Flying','[ InnerFocus - Multiscale ]'),
('Mewtwo','Psychic','','[ Pressure - Unnerve ]'),
('Mew','Psychic','','[ Synchronize ]'),
('Chikorita','Grass','','[ LeafGuard - Overgrow ]'),
('Bayleef','Grass','','[ LeafGuard - Overgrow ]'),
('Meganium','Grass','','[ LeafGuard - Overgrow ]'),
('Cyndaquil','Fire','','[ Blaze - FlashFire ]'),
('Quilava','Fire','','[ Blaze - FlashFire ]'),
('Typhlosion','Fire','','[ Blaze - FlashFire ]'),
('Totodile','Water','','[ SheerForce - Torrent ]'),
('Croconaw','Water','','[ SheerForce - Torrent ]'),
('Feraligatr','Water','','[ SheerForce - Torrent ]'),
('Sentret','Normal','','[ Frisk - KeenEye - RunAway ]'),
('Furret','Normal','','[ Frisk - KeenEye - RunAway ]'),
('Hoothoot','Normal','Flying','[ Insomnia - KeenEye - TintedLens ]'),
('Noctowl','Normal','Flying','[ Insomnia - KeenEye - TintedLens ]'),
('Ledyba','Bug','Flying','[ EarlyBird - Rattled - Swarm ]'),
('Ledian','Bug','Flying','[ EarlyBird - IronFist - Swarm ]'),
('Spinarak','Bug','Poison','[ Insomnia - Sniper - Swarm ]'),
('Ariados','Bug','Poison','[ Insomnia - Sniper - Swarm ]'),
('Crobat','Poison','Flying','[ Infiltrator - InnerFocus ]'),
('Chinchou','Water','Electric','[ Illuminate - VoltAbsorb - WaterAbsorb ]'),
('Lanturn','Water','Electric','[ Illuminate - VoltAbsorb - WaterAbsorb ]'),
('Pichu','Electric','','[ LightningRod - Static ]'),
('Cleffa','Fairy','','[ CuteCharm - FriendGuard - MagicGuard ]'),
('Igglybuff','Normal','Fairy','[ Competitive - CuteCharm - FriendGuard ]'),
('Togepi','Fairy','','[ Hustle - SereneGrace - SuperLuck ]'),
('Togetic','Fairy','Flying','[ Hustle - SereneGrace - SuperLuck ]'),
('Natu','Psychic','Flying','[ EarlyBird - MagicBounce - Synchronize ]'),
('Xatu','Psychic','Flying','[ EarlyBird - MagicBounce - Synchronize ]'),
('Mareep','Electric','','[ Plus - Static ]'),
('Flaaffy','Electric','','[ Plus - Static ]'),
('Ampharos','Electric','','[ Plus - Static ]'),
('Bellossom','Grass','','[ Chlorophyll - Healer ]'),
('Marill','Water','Fairy','[ HugePower - SapSipper - ThickFat ]'),
('Azumarill','Water','Fairy','[ HugePower - SapSipper - ThickFat ]'),
('Sudowoodo','Rock','','[ Rattled - RockHead - Sturdy ]'),
('Politoed','Water','','[ Damp - Drizzle - WaterAbsorb ]'),
('Hoppip','Grass','Flying','[ Chlorophyll - Infiltrator - LeafGuard ]'),
('Skiploom','Grass','Flying','[ Chlorophyll - Infiltrator - LeafGuard ]'),
('Jumpluff','Grass','Flying','[ Chlorophyll - Infiltrator - LeafGuard ]'),
('Aipom','Normal','','[ Pickup - RunAway - SkillLink ]'),
('Sunkern','Grass','','[ Chlorophyll - EarlyBird - SolarPower ]'),
('Sunflora','Grass','','[ Chlorophyll - EarlyBird - SolarPower ]'),
('Yanma','Bug','Flying','[ Frisk - SpeedBoost ]'),
('Wooper','Water','Ground','[ Damp - Unaware - WaterAbsorb ]'),
('Quagsire','Water','Ground','[ Damp - Unaware - WaterAbsorb ]'),
('Espeon','Psychic','','[ MagicBounce - Synchronize ]'),
('Umbreon','Dark','','[ InnerFocus - Synchronize ]'),
('Murkrow','Dark','Flying','[ Insomnia - Prankster - SuperLuck ]'),
('Slowking','Water','Psychic','[ Oblivious - OwnTempo - Regenerator ]'),
('Misdreavus','Ghost','','[ Levitate ]'),
('Unown','Psychic','','[ Levitate ]'),
('Wobbuffet','Psychic','','[ ShadowTag - Telepathy ]'),
('Girafarig','Normal','Psychic','[ EarlyBird - InnerFocus - SapSipper ]'),
('Pineco','Bug','','[ Overcoat - Sturdy ]'),
('Forretress','Bug','Steel','[ Overcoat - Sturdy ]'),
('Dunsparce','Normal','','[ Rattled - RunAway - SereneGrace ]'),
('Gligar','Ground','Flying','[ HyperCutter - Immunity - SandVeil ]'),
('Steelix','Steel','Ground','[ RockHead - SheerForce - Sturdy ]'),
('Snubbull','Fairy','','[ Intimidate - Rattled - RunAway ]'),
('Granbull','Fairy','','[ Intimidate - QuickFeet - Rattled ]'),
('Qwilfish','Water','Poison','[ Intimidate - PoisonPoint - SwiftSwim ]'),
('Scizor','Bug','Steel','[ LightMetal - Swarm - Technician ]'),
('Shuckle','Bug','Rock','[ Contrary - Gluttony - Sturdy ]'),
('Heracross','Bug','Fighting','[ Guts - Moxie - Swarm ]'),
('Sneasel','Dark','Ice','[ InnerFocus - KeenEye - Pickpocket ]'),
('Teddiursa','Normal','','[ HoneyGather - Pickup - QuickFeet ]'),
('Ursaring','Normal','','[ Guts - QuickFeet - Unnerve ]'),
('Slugma','Fire','','[ FlameBody - MagmaArmor - WeakArmor ]'),
('Magcargo','Fire','Rock','[ FlameBody - MagmaArmor - WeakArmor ]'),
('Swinub','Ice','Ground','[ Oblivious - SnowCloak - ThickFat ]'),
('Piloswine','Ice','Ground','[ Oblivious - SnowCloak - ThickFat ]'),
('Corsola','Water','Rock','[ Hustle - NaturalCure - Regenerator ]'),
('Remoraid','Water','','[ Hustle - Moody - Sniper ]'),
('Octillery','Water','','[ Moody - Sniper - SuctionCups ]'),
('Delibird','Ice','Flying','[ Hustle - Insomnia - VitalSpirit ]'),
('Mantine','Water','Flying','[ SwiftSwim - WaterAbsorb - WaterVeil ]'),
('Skarmory','Steel','Flying','[ KeenEye - Sturdy - WeakArmor ]'),
('Houndour','Dark','Fire','[ EarlyBird - FlashFire - Unnerve ]'),
('Houndoom','Dark','Fire','[ EarlyBird - FlashFire - Unnerve ]'),
('Kingdra','Water','Dragon','[ Damp - Sniper - SwiftSwim ]'),
('Phanpy','Ground','','[ Pickup - SandVeil ]'),
('Donphan','Ground','','[ SandVeil - Sturdy ]'),
('Porygon2','Normal','','[ Analytic - Download - Trace ]'),
('Stantler','Normal','','[ Frisk - Intimidate - SapSipper ]'),
('Smeargle','Normal','','[ Moody - OwnTempo - Technician ]'),
('Tyrogue','Fighting','','[ Guts - Steadfast - VitalSpirit ]'),
('Hitmontop','Fighting','','[ Intimidate - Steadfast - Technician ]'),
('Smoochum','Ice','Psychic','[ Forewarn - Hydration - Oblivious ]'),
('Elekid','Electric','','[ Static - VitalSpirit ]'),
('Magby','Fire','','[ FlameBody - VitalSpirit ]'),
('Miltank','Normal','','[ SapSipper - Scrappy - ThickFat ]'),
('Blissey','Normal','','[ Healer - NaturalCure - SereneGrace ]'),
('Raikou','Electric','','[ InnerFocus - Pressure ]'),
('Entei','Fire','','[ InnerFocus - Pressure ]'),
('Suicune','Water','','[ InnerFocus - Pressure ]'),
('Larvitar','Rock','Ground','[ Guts - SandVeil ]'),
('Pupitar','Rock','Ground','[ ShedSkin ]'),
('Tyranitar','Rock','Dark','[ SandStream - Unnerve ]'),
('Lugia','Psychic','Flying','[ Multiscale - Pressure ]'),
('Ho-Oh','Fire','Flying','[ Pressure - Regenerator ]'),
('Celebi','Psychic','Grass','[ NaturalCure ]'),
('Treecko','Grass','','[ Overgrow - Unburden ]'),
('Grovyle','Grass','','[ Overgrow - Unburden ]'),
('Sceptile','Grass','','[ Overgrow - Unburden ]'),
('Torchic','Fire','','[ Blaze - SpeedBoost ]'),
('Combusken','Fire','Fighting','[ Blaze - SpeedBoost ]'),
('Blaziken','Fire','Fighting','[ Blaze - SpeedBoost ]'),
('Mudkip','Water','','[ Damp - Torrent ]'),
('Marshtomp','Water','Ground','[ Damp - Torrent ]'),
('Swampert','Water','Ground','[ Damp - Torrent ]'),
('Poochyena','Dark','','[ QuickFeet - Rattled - RunAway ]'),
('Mightyena','Dark','','[ Intimidate - Moxie - QuickFeet ]'),
('Zigzagoon','Normal','','[ Gluttony - Pickup - QuickFeet ]'),
('Linoone','Normal','','[ Gluttony - Pickup - QuickFeet ]'),
('Wurmple','Bug','','[ RunAway - ShieldDust ]'),
('Silcoon','Bug','','[ ShedSkin ]'),
('Beautifly','Bug','Flying','[ Rivalry - Swarm ]'),
('Cascoon','Bug','','[ ShedSkin ]'),
('Dustox','Bug','Poison','[ ShieldDust ]'),
('Lotad','Water','Grass','[ OwnTempo - RainDish - SwiftSwim ]'),
('Lombre','Water','Grass','[ OwnTempo - RainDish - SwiftSwim ]'),
('Ludicolo','Water','Grass','[ OwnTempo - RainDish - SwiftSwim ]'),
('Seedot','Grass','','[ Chlorophyll - EarlyBird - Pickpocket ]'),
('Nuzleaf','Grass','Dark','[ Chlorophyll - EarlyBird - Pickpocket ]'),
('Shiftry','Grass','Dark','[ Chlorophyll - EarlyBird - Pickpocket ]'),
('Taillow','Normal','Flying','[ Guts - Scrappy ]'),
('Swellow','Normal','Flying','[ Guts - Scrappy ]'),
('Wingull','Water','Flying','[ Hydration - KeenEye - RainDish ]'),
('Pelipper','Water','Flying','[ Drizzle - KeenEye - RainDish ]'),
('Ralts','Psychic','Fairy','[ Synchronize - Telepathy - Trace ]'),
('Kirlia','Psychic','Fairy','[ Synchronize - Telepathy - Trace ]'),
('Gardevoir','Psychic','Fairy','[ Synchronize - Telepathy - Trace ]'),
('Surskit','Bug','Water','[ RainDish - SwiftSwim ]'),
('Masquerain','Bug','Flying','[ Intimidate - Unnerve ]'),
('Shroomish','Grass','','[ EffectSpore - PoisonHeal - QuickFeet ]'),
('Breloom','Grass','Fighting','[ EffectSpore - PoisonHeal - Technician ]'),
('Slakoth','Normal','','[ Truant ]'),
('Vigoroth','Normal','','[ VitalSpirit ]'),
('Slaking','Normal','','[ Truant ]'),
('Nincada','Bug','Ground','[ RunAway ]'),
('Ninjask','Bug','Flying','[ Infiltrator - SpeedBoost ]'),
('Shedinja','Bug','Ghost','[ WonderGuard ]'),
('Whismur','Normal','','[ Rattled - Soundproof ]'),
('Loudred','Normal','','[ Scrappy - Soundproof ]'),
('Exploud','Normal','','[ Scrappy - Soundproof ]'),
('Makuhita','Fighting','','[ Guts - SheerForce - ThickFat ]'),
('Hariyama','Fighting','','[ Guts - SheerForce - ThickFat ]'),
('Azurill','Normal','Fairy','[ HugePower - SapSipper - ThickFat ]'),
('Nosepass','Rock','','[ MagnetPull - SandForce - Sturdy ]'),
('Skitty','Normal','','[ CuteCharm - Normalize - WonderSkin ]'),
('Delcatty','Normal','','[ CuteCharm - Normalize - WonderSkin ]'),
('Sableye','Dark','Ghost','[ KeenEye - Prankster - Stall ]'),
('Mawile','Steel','Fairy','[ HyperCutter - Intimidate - SheerForce ]'),
('Aron','Steel','Rock','[ HeavyMetal - RockHead - Sturdy ]'),
('Lairon','Steel','Rock','[ HeavyMetal - RockHead - Sturdy ]'),
('Aggron','Steel','Rock','[ HeavyMetal - RockHead - Sturdy ]'),
('Meditite','Fighting','Psychic','[ PurePower - Telepathy ]'),
('Medicham','Fighting','Psychic','[ PurePower - Telepathy ]'),
('Electrike','Electric','','[ LightningRod - Minus - Static ]'),
('Manectric','Electric','','[ LightningRod - Minus - Static ]'),
('Plusle','Electric','','[ LightningRod - Plus ]'),
('Minun','Electric','','[ Minus - VoltAbsorb ]'),
('Volbeat','Bug','','[ Illuminate - Prankster - Swarm ]'),
('Illumise','Bug','','[ Oblivious - Prankster - TintedLens ]'),
('Roselia','Grass','Poison','[ LeafGuard - NaturalCure - PoisonPoint ]'),
('Gulpin','Poison','','[ Gluttony - LiquidOoze - StickyHold ]'),
('Swalot','Poison','','[ Gluttony - LiquidOoze - StickyHold ]'),
('Carvanha','Water','Dark','[ RoughSkin - SpeedBoost ]'),
('Sharpedo','Water','Dark','[ RoughSkin - SpeedBoost ]'),
('Wailmer','Water','','[ Oblivious - Pressure - WaterVeil ]'),
('Wailord','Water','','[ Oblivious - Pressure - WaterVeil ]'),
('Numel','Fire','Ground','[ Oblivious - OwnTempo - Simple ]'),
('Camerupt','Fire','Ground','[ AngerPoint - MagmaArmor - SolidRock ]'),
('Torkoal','Fire','','[ Drought - ShellArmor - WhiteSmoke ]'),
('Spoink','Psychic','','[ Gluttony - OwnTempo - ThickFat ]'),
('Grumpig','Psychic','','[ Gluttony - OwnTempo - ThickFat ]'),
('Spinda','Normal','','[ Contrary - OwnTempo - TangledFeet ]'),
('Trapinch','Ground','','[ ArenaTrap - HyperCutter - SheerForce ]'),
('Vibrava','Ground','Dragon','[ Levitate ]'),
('Flygon','Ground','Dragon','[ Levitate ]'),
('Cacnea','Grass','','[ SandVeil - WaterAbsorb ]'),
('Cacturne','Grass','Dark','[ SandVeil - WaterAbsorb ]'),
('Swablu','Normal','Flying','[ CloudNine - NaturalCure ]'),
('Altaria','Dragon','Flying','[ CloudNine - NaturalCure ]'),
('Zangoose','Normal','','[ Immunity - ToxicBoost ]'),
('Seviper','Poison','','[ Infiltrator - ShedSkin ]'),
('Lunatone','Rock','Psychic','[ Levitate ]'),
('Solrock','Rock','Psychic','[ Levitate ]'),
('Barboach','Water','Ground','[ Anticipation - Hydration - Oblivious ]'),
('Whiscash','Water','Ground','[ Anticipation - Hydration - Oblivious ]'),
('Corphish','Water','','[ Adaptability - HyperCutter - ShellArmor ]'),
('Crawdaunt','Water','Dark','[ Adaptability - HyperCutter - ShellArmor ]'),
('Baltoy','Ground','Psychic','[ Levitate ]'),
('Claydol','Ground','Psychic','[ Levitate ]'),
('Lileep','Rock','Grass','[ StormDrain - SuctionCups ]'),
('Cradily','Rock','Grass','[ StormDrain - SuctionCups ]'),
('Anorith','Rock','Bug','[ BattleArmor - SwiftSwim ]'),
('Armaldo','Rock','Bug','[ BattleArmor - SwiftSwim ]'),
('Feebas','Water','','[ Adaptability - Oblivious - SwiftSwim ]'),
('Milotic','Water','','[ Competitive - CuteCharm - MarvelScale ]'),
('Castform','Normal','','[ Forecast ]'),
('Kecleon','Normal','','[ ColorChange - Protean ]'),
('Shuppet','Ghost','','[ CursedBody - Frisk - Insomnia ]'),
('Banette','Ghost','','[ CursedBody - Frisk - Insomnia ]'),
('Duskull','Ghost','','[ Frisk - Levitate ]'),
('Dusclops','Ghost','','[ Frisk - Pressure ]'),
('Tropius','Grass','Flying','[ Chlorophyll - Harvest - SolarPower ]'),
('Chimecho','Psychic','','[ Levitate ]'),
('Absol','Dark','','[ Justified - Pressure - SuperLuck ]'),
('Wynaut','Psychic','','[ ShadowTag - Telepathy ]'),
('Snorunt','Ice','','[ IceBody - InnerFocus - Moody ]'),
('Glalie','Ice','','[ IceBody - InnerFocus - Moody ]'),
('Spheal','Ice','Water','[ IceBody - Oblivious - ThickFat ]'),
('Sealeo','Ice','Water','[ IceBody - Oblivious - ThickFat ]'),
('Walrein','Ice','Water','[ IceBody - Oblivious - ThickFat ]'),
('Clamperl','Water','','[ Rattled - ShellArmor ]'),
('Huntail','Water','','[ SwiftSwim - WaterVeil ]'),
('Gorebyss','Water','','[ Hydration - SwiftSwim ]'),
('Relicanth','Water','Rock','[ RockHead - Sturdy - SwiftSwim ]'),
('Luvdisc','Water','','[ Hydration - SwiftSwim ]'),
('Bagon','Dragon','','[ RockHead - SheerForce ]'),
('Shelgon','Dragon','','[ Overcoat - RockHead ]'),
('Salamence','Dragon','Flying','[ Intimidate - Moxie ]'),
('Beldum','Steel','Psychic','[ ClearBody - LightMetal ]'),
('Metang','Steel','Psychic','[ ClearBody - LightMetal ]'),
('Metagross','Steel','Psychic','[ ClearBody - LightMetal ]'),
('Regirock','Rock','','[ ClearBody - Sturdy ]'),
('Regice','Ice','','[ ClearBody - IceBody ]'),
('Registeel','Steel','','[ ClearBody - LightMetal ]'),
('Latias','Dragon','Psychic','[ Levitate ]'),
('Latios','Dragon','Psychic','[ Levitate ]'),
('Kyogre','Water','','[ Drizzle ]'),
('Groudon','Ground','','[ Drought ]'),
('Rayquaza','Dragon','Flying','[ AirLock ]'),
('Jirachi','Steel','Psychic','[ SereneGrace ]'),
('Deoxys Normal Form','Psychic','','[ Pressure ]'),
('Turtwig','Grass','','[ Overgrow - ShellArmor ]'),
('Grotle','Grass','','[ Overgrow - ShellArmor ]'),
('Torterra','Grass','Ground','[ Overgrow - ShellArmor ]'),
('Chimchar','Fire','','[ Blaze - IronFist ]'),
('Monferno','Fire','Fighting','[ Blaze - IronFist ]'),
('Infernape','Fire','Fighting','[ Blaze - IronFist ]'),
('Piplup','Water','','[ Defiant - Torrent ]'),
('Prinplup','Water','','[ Defiant - Torrent ]'),
('Empoleon','Water','Steel','[ Defiant - Torrent ]'),
('Starly','Normal','Flying','[ KeenEye - Reckless ]'),
('Staravia','Normal','Flying','[ Intimidate - Reckless ]'),
('Staraptor','Normal','Flying','[ Intimidate - Reckless ]'),
('Bidoof','Normal','','[ Moody - Simple - Unaware ]'),
('Bibarel','Normal','Water','[ Moody - Simple - Unaware ]'),
('Kricketot','Bug','','[ RunAway - ShedSkin ]'),
('Kricketune','Bug','','[ Swarm - Technician ]'),
('Shinx','Electric','','[ Guts - Intimidate - Rivalry ]'),
('Luxio','Electric','','[ Guts - Intimidate - Rivalry ]'),
('Luxray','Electric','','[ Guts - Intimidate - Rivalry ]'),
('Budew','Grass','Poison','[ LeafGuard - NaturalCure - PoisonPoint ]'),
('Roserade','Grass','Poison','[ NaturalCure - PoisonPoint - Technician ]'),
('Cranidos','Rock','','[ MoldBreaker - SheerForce ]'),
('Rampardos','Rock','','[ MoldBreaker - SheerForce ]'),
('Shieldon','Rock','Steel','[ Soundproof - Sturdy ]'),
('Bastiodon','Rock','Steel','[ Soundproof - Sturdy ]'),
('Burmy','Bug','','[ Overcoat - ShedSkin ]'),
('Wormadam Plant Cloak','Bug','Grass','[ Anticipation - Overcoat ]'),
('Mothim','Bug','Flying','[ Swarm - TintedLens ]'),
('Combee','Bug','Flying','[ HoneyGather - Hustle ]'),
('Vespiquen','Bug','Flying','[ Pressure - Unnerve ]'),
('Pachirisu','Electric','','[ Pickup - RunAway - VoltAbsorb ]'),
('Buizel','Water','','[ SwiftSwim - WaterVeil ]'),
('Floatzel','Water','','[ SwiftSwim - WaterVeil ]'),
('Cherubi','Grass','','[ Chlorophyll ]'),
('Cherrim','Grass','','[ FlowerGift ]'),
('Shellos','Water','','[ SandForce - StickyHold - StormDrain ]'),
('Gastrodon','Water','Ground','[ SandForce - StickyHold - StormDrain ]'),
('Ambipom','Normal','','[ Pickup - SkillLink - Technician ]'),
('Drifloon','Ghost','Flying','[ Aftermath - FlareBoost - Unburden ]'),
('Drifblim','Ghost','Flying','[ Aftermath - FlareBoost - Unburden ]'),
('Buneary','Normal','','[ Klutz - Limber - RunAway ]'),
('Lopunny','Normal','','[ CuteCharm - Klutz - Limber ]'),
('Mismagius','Ghost','','[ Levitate ]'),
('Honchkrow','Dark','Flying','[ Insomnia - Moxie - SuperLuck ]'),
('Glameow','Normal','','[ KeenEye - Limber - OwnTempo ]'),
('Purugly','Normal','','[ Defiant - OwnTempo - ThickFat ]'),
('Chingling','Psychic','','[ Levitate ]'),
('Stunky','Poison','Dark','[ Aftermath - KeenEye - Stench ]'),
('Skuntank','Poison','Dark','[ Aftermath - KeenEye - Stench ]'),
('Bronzor','Steel','Psychic','[ Heatproof - HeavyMetal - Levitate ]'),
('Bronzong','Steel','Psychic','[ Heatproof - HeavyMetal - Levitate ]'),
('Bonsly','Rock','','[ Rattled - RockHead - Sturdy ]'),
('Mime Jr.','Psychic','Fairy','[ Filter - Soundproof - Technician ]'),
('Happiny','Normal','','[ FriendGuard - NaturalCure - SereneGrace ]'),
('Chatot','Normal','Flying','[ BigPecks - KeenEye - TangledFeet ]'),
('Spiritomb','Ghost','Dark','[ Infiltrator - Pressure ]'),
('Gible','Dragon','Ground','[ RoughSkin - SandVeil ]'),
('Gabite','Dragon','Ground','[ RoughSkin - SandVeil ]'),
('Garchomp','Dragon','Ground','[ RoughSkin - SandVeil ]'),
('Munchlax','Normal','','[ Gluttony - Pickup - ThickFat ]'),
('Riolu','Fighting','','[ InnerFocus - Prankster - Steadfast ]'),
('Lucario','Fighting','Steel','[ InnerFocus - Justified - Steadfast ]'),
('Hippopotas','Ground','','[ SandForce - SandStream ]'),
('Hippowdon','Ground','','[ SandForce - SandStream ]'),
('Skorupi','Poison','Bug','[ BattleArmor - KeenEye - Sniper ]'),
('Drapion','Poison','Dark','[ BattleArmor - KeenEye - Sniper ]'),
('Croagunk','Poison','Fighting','[ Anticipation - DrySkin - PoisonTouch ]'),
('Toxicroak','Poison','Fighting','[ Anticipation - DrySkin - PoisonTouch ]'),
('Carnivine','Grass','','[ Levitate ]'),
('Finneon','Water','','[ StormDrain - SwiftSwim - WaterVeil ]'),
('Lumineon','Water','','[ StormDrain - SwiftSwim - WaterVeil ]'),
('Mantyke','Water','Flying','[ SwiftSwim - WaterAbsorb - WaterVeil ]'),
('Snover','Grass','Ice','[ SnowWarning - Soundproof ]'),
('Abomasnow','Grass','Ice','[ SnowWarning - Soundproof ]'),
('Weavile','Dark','Ice','[ Pickpocket - Pressure ]'),
('Magnezone','Electric','Steel','[ Analytic - MagnetPull - Sturdy ]'),
('Lickilicky','Normal','','[ CloudNine - Oblivious - OwnTempo ]'),
('Rhyperior','Ground','Rock','[ LightningRod - Reckless - SolidRock ]'),
('Tangrowth','Grass','','[ Chlorophyll - LeafGuard - Regenerator ]'),
('Electivire','Electric','','[ MotorDrive - VitalSpirit ]'),
('Magmortar','Fire','','[ FlameBody - VitalSpirit ]'),
('Togekiss','Fairy','Flying','[ Hustle - SereneGrace - SuperLuck ]'),
('Yanmega','Bug','Flying','[ Frisk - SpeedBoost - TintedLens ]'),
('Leafeon','Grass','','[ Chlorophyll - LeafGuard ]'),
('Glaceon','Ice','','[ IceBody - SnowCloak ]'),
('Gliscor','Ground','Flying','[ HyperCutter - PoisonHeal - SandVeil ]'),
('Mamoswine','Ice','Ground','[ Oblivious - SnowCloak - ThickFat ]'),
('Porygon-Z','Normal','','[ Adaptability - Analytic - Download ]'),
('Gallade','Psychic','Fighting','[ Justified - Steadfast ]'),
('Probopass','Rock','Steel','[ MagnetPull - SandForce - Sturdy ]'),
('Dusknoir','Ghost','','[ Frisk - Pressure ]'),
('Froslass','Ice','Ghost','[ CursedBody - SnowCloak ]'),
('Rotom','Electric','Ghost','[ Levitate ]'),
('Uxie','Psychic','','[ Levitate ]'),
('Mesprit','Psychic','','[ Levitate ]'),
('Azelf','Psychic','','[ Levitate ]'),
('Dialga','Steel','Dragon','[ Pressure - Telepathy ]'),
('Palkia','Water','Dragon','[ Pressure - Telepathy ]'),
('Heatran','Fire','Steel','[ FlameBody - FlashFire ]'),
('Regigigas','Normal','','[ SlowStart ]'),
('Giratina','Ghost','Dragon','[ Pressure - Telepathy ]'),
('Cresselia','Psychic','','[ Levitate ]'),
('Phione','Water','','[ Hydration ]'),
('Manaphy','Water','','[ Hydration ]'),
('Darkrai','Dark','','[ BadDreams ]'),
('Shaymin','Grass','','[ NaturalCure ]'),
('Arceus','Normal','','[ Multitype ]'),
('Victini','Psychic','Fire','[ VictoryStar ]'),
('Snivy','Grass','','[ Contrary - Overgrow ]'),
('Servine','Grass','','[ Contrary - Overgrow ]'),
('Serperior','Grass','','[ Contrary - Overgrow ]'),
('Tepig','Fire','','[ Blaze - ThickFat ]'),
('Pignite','Fire','Fighting','[ Blaze - ThickFat ]'),
('Emboar','Fire','Fighting','[ Blaze - Reckless ]'),
('Oshawott','Water','','[ ShellArmor - Torrent ]'),
('Dewott','Water','','[ ShellArmor - Torrent ]'),
('Samurott','Water','','[ ShellArmor - Torrent ]'),
('Patrat','Normal','','[ Analytic - KeenEye - RunAway ]'),
('Watchog','Normal','','[ Analytic - Illuminate - KeenEye ]'),
('Lillipup','Normal','','[ Pickup - RunAway - VitalSpirit ]'),
('Herdier','Normal','','[ Intimidate - SandRush - Scrappy ]'),
('Stoutland','Normal','','[ Intimidate - SandRush - Scrappy ]'),
('Purrloin','Dark','','[ Limber - Prankster - Unburden ]'),
('Liepard','Dark','','[ Limber - Prankster - Unburden ]'),
('Pansage','Grass','','[ Gluttony - Overgrow ]'),
('Simisage','Grass','','[ Gluttony - Overgrow ]'),
('Pansear','Fire','','[ Blaze - Gluttony ]'),
('Simisear','Fire','','[ Blaze - Gluttony ]'),
('Panpour','Water','','[ Gluttony - Torrent ]'),
('Simipour','Water','','[ Gluttony - Torrent ]'),
('Munna','Psychic','','[ Forewarn - Synchronize - Telepathy ]'),
('Musharna','Psychic','','[ Forewarn - Synchronize - Telepathy ]'),
('Pidove','Normal','Flying','[ BigPecks - Rivalry - SuperLuck ]'),
('Tranquill','Normal','Flying','[ BigPecks - Rivalry - SuperLuck ]'),
('Unfezant','Normal','Flying','[ BigPecks - Rivalry - SuperLuck ]'),
('Blitzle','Electric','','[ LightningRod - MotorDrive - SapSipper ]'),
('Zebstrika','Electric','','[ LightningRod - MotorDrive - SapSipper ]'),
('Roggenrola','Rock','','[ SandForce - Sturdy - WeakArmor ]'),
('Boldore','Rock','','[ SandForce - Sturdy - WeakArmor ]'),
('Gigalith','Rock','','[ SandForce - SandStream - Sturdy ]'),
('Woobat','Psychic','Flying','[ Klutz - Simple - Unaware ]'),
('Swoobat','Psychic','Flying','[ Klutz - Simple - Unaware ]'),
('Drilbur','Ground','','[ MoldBreaker - SandForce - SandRush ]'),
('Excadrill','Ground','Steel','[ MoldBreaker - SandForce - SandRush ]'),
('Audino','Normal','','[ Healer - Klutz - Regenerator ]'),
('Timburr','Fighting','','[ Guts - IronFist - SheerForce ]'),
('Gurdurr','Fighting','','[ Guts - IronFist - SheerForce ]'),
('Conkeldurr','Fighting','','[ Guts - IronFist - SheerForce ]'),
('Tympole','Water','','[ Hydration - SwiftSwim - WaterAbsorb ]'),
('Palpitoad','Water','Ground','[ Hydration - SwiftSwim - WaterAbsorb ]'),
('Seismitoad','Water','Ground','[ PoisonTouch - SwiftSwim - WaterAbsorb ]'),
('Throh','Fighting','','[ Guts - InnerFocus - MoldBreaker ]'),
('Sawk','Fighting','','[ InnerFocus - MoldBreaker - Sturdy ]'),
('Sewaddle','Bug','Grass','[ Chlorophyll - Overcoat - Swarm ]'),
('Swadloon','Bug','Grass','[ Chlorophyll - LeafGuard - Overcoat ]'),
('Leavanny','Bug','Grass','[ Chlorophyll - Overcoat - Swarm ]'),
('Venipede','Bug','Poison','[ PoisonPoint - SpeedBoost - Swarm ]'),
('Whirlipede','Bug','Poison','[ PoisonPoint - SpeedBoost - Swarm ]'),
('Scolipede','Bug','Poison','[ PoisonPoint - SpeedBoost - Swarm ]'),
('Cottonee','Grass','Fairy','[ Chlorophyll - Infiltrator - Prankster ]'),
('Whimsicott','Grass','Fairy','[ Chlorophyll - Infiltrator - Prankster ]'),
('Petilil','Grass','','[ Chlorophyll - LeafGuard - OwnTempo ]'),
('Lilligant','Grass','','[ Chlorophyll - LeafGuard - OwnTempo ]'),
('Basculin','Water','','[ Adaptability - MoldBreaker - Reckless ]'),
('Sandile','Ground','Dark','[ AngerPoint - Intimidate - Moxie ]'),
('Krokorok','Ground','Dark','[ AngerPoint - Intimidate - Moxie ]'),
('Krookodile','Ground','Dark','[ AngerPoint - Intimidate - Moxie ]'),
('Darumaka','Fire','','[ Hustle - InnerFocus ]'),
('Darmanitan','Fire','','[ SheerForce - ZenMode ]'),
('Maractus','Grass','','[ Chlorophyll - StormDrain - WaterAbsorb ]'),
('Dwebble','Bug','Rock','[ ShellArmor - Sturdy - WeakArmor ]'),
('Crustle','Bug','Rock','[ ShellArmor - Sturdy - WeakArmor ]'),
('Scraggy','Dark','Fighting','[ Intimidate - Moxie - ShedSkin ]'),
('Scrafty','Dark','Fighting','[ Intimidate - Moxie - ShedSkin ]'),
('Sigilyph','Psychic','Flying','[ MagicGuard - TintedLens - WonderSkin ]'),
('Yamask','Ghost','','[ Mummy ]'),
('Cofagrigus','Ghost','','[ Mummy ]'),
('Tirtouga','Water','Rock','[ SolidRock - Sturdy - SwiftSwim ]'),
('Carracosta','Water','Rock','[ SolidRock - Sturdy - SwiftSwim ]'),
('Archen','Rock','Flying','[ Defeatist ]'),
('Archeops','Rock','Flying','[ Defeatist ]'),
('Trubbish','Poison','','[ Aftermath - Stench - StickyHold ]'),
('Garbodor','Poison','','[ Aftermath - Stench - WeakArmor ]'),
('Zorua','Dark','','[ Illusion ]'),
('Zoroark','Dark','','[ Illusion ]'),
('Minccino','Normal','','[ CuteCharm - SkillLink - Technician ]'),
('Cinccino','Normal','','[ CuteCharm - SkillLink - Technician ]'),
('Gothita','Psychic','','[ Competitive - Frisk - ShadowTag ]'),
('Gothorita','Psychic','','[ Competitive - Frisk - ShadowTag ]'),
('Gothitelle','Psychic','','[ Competitive - Frisk - ShadowTag ]'),
('Solosis','Psychic','','[ MagicGuard - Overcoat - Regenerator ]'),
('Duosion','Psychic','','[ MagicGuard - Overcoat - Regenerator ]'),
('Reuniclus','Psychic','','[ MagicGuard - Overcoat - Regenerator ]'),
('Ducklett','Water','Flying','[ BigPecks - Hydration - KeenEye ]'),
('Swanna','Water','Flying','[ BigPecks - Hydration - KeenEye ]'),
('Vanillite','Ice','','[ IceBody - SnowCloak - WeakArmor ]'),
('Vanillish','Ice','','[ IceBody - SnowCloak - WeakArmor ]'),
('Vanilluxe','Ice','','[ IceBody - SnowWarning - WeakArmor ]'),
('Deerling','Normal','Grass','[ Chlorophyll - SapSipper - SereneGrace ]'),
('Sawsbuck','Normal','Grass','[ Chlorophyll - SapSipper - SereneGrace ]'),
('Emolga','Electric','Flying','[ MotorDrive - Static ]'),
('Karrablast','Bug','','[ NoGuard - ShedSkin - Swarm ]'),
('Escavalier','Bug','Steel','[ Overcoat - ShellArmor - Swarm ]'),
('Foongus','Grass','Poison','[ EffectSpore - Regenerator ]'),
('Amoonguss','Grass','Poison','[ EffectSpore - Regenerator ]'),
('Frillish','Water','Ghost','[ CursedBody - Damp - WaterAbsorb ]'),
('Jellicent','Water','Ghost','[ CursedBody - Damp - WaterAbsorb ]'),
('Alomomola','Water','','[ Healer - Hydration - Regenerator ]'),
('Joltik','Bug','Electric','[ Swarm - Unnerve ]'),
('Galvantula','Bug','Electric','[ Swarm - Unnerve ]'),
('Ferroseed','Grass','Steel','[ IronBarbs ]'),
('Ferrothorn','Grass','Steel','[ Anticipation - IronBarbs ]'),
('Klink','Steel','','[ ClearBody - Minus - Plus ]'),
('Klang','Steel','','[ ClearBody - Minus - Plus ]'),
('Klinklang','Steel','','[ ClearBody - Minus - Plus ]'),
('Tynamo','Electric','','[ Levitate ]'),
('Eelektrik','Electric','','[ Levitate ]'),
('Eelektross','Electric','','[ Levitate ]'),
('Elgyem','Psychic','','[ Analytic - Synchronize - Telepathy ]'),
('Beheeyem','Psychic','','[ Analytic - Synchronize - Telepathy ]'),
('Litwick','Ghost','Fire','[ FlameBody - FlashFire - Infiltrator ]'),
('Lampent','Ghost','Fire','[ FlameBody - FlashFire - Infiltrator ]'),
('Chandelure','Ghost','Fire','[ FlameBody - FlashFire - Infiltrator ]'),
('Axew','Dragon','','[ MoldBreaker - Rivalry - Unnerve ]'),
('Fraxure','Dragon','','[ MoldBreaker - Rivalry - Unnerve ]'),
('Haxorus','Dragon','','[ MoldBreaker - Rivalry - Unnerve ]'),
('Cubchoo','Ice','','[ Rattled - SlushRush - SnowCloak ]'),
('Beartic','Ice','','[ SlushRush - SnowCloak - SwiftSwim ]'),
('Cryogonal','Ice','','[ Levitate ]'),
('Shelmet','Bug','','[ Hydration - Overcoat - ShellArmor ]'),
('Accelgor','Bug','','[ Hydration - StickyHold - Unburden ]'),
('Stunfisk','Ground','Electric','[ Limber - SandVeil - Static ]'),
('Mienfoo','Fighting','','[ InnerFocus - Reckless - Regenerator ]'),
('Mienshao','Fighting','','[ InnerFocus - Reckless - Regenerator ]'),
('Druddigon','Dragon','','[ MoldBreaker - RoughSkin - SheerForce ]'),
('Golett','Ground','Ghost','[ IronFist - Klutz - NoGuard ]'),
('Golurk','Ground','Ghost','[ IronFist - Klutz - NoGuard ]'),
('Pawniard','Dark','Steel','[ Defiant - InnerFocus - Pressure ]'),
('Bisharp','Dark','Steel','[ Defiant - InnerFocus - Pressure ]'),
('Bouffalant','Normal','','[ Reckless - SapSipper - Soundproof ]'),
('Rufflet','Normal','Flying','[ Hustle - KeenEye - SheerForce ]'),
('Braviary','Normal','Flying','[ Defiant - KeenEye - SheerForce ]'),
('Vullaby','Dark','Flying','[ BigPecks - Overcoat - WeakArmor ]'),
('Mandibuzz','Dark','Flying','[ BigPecks - Overcoat - WeakArmor ]'),
('Heatmor','Fire','','[ FlashFire - Gluttony - WhiteSmoke ]'),
('Durant','Bug','Steel','[ Hustle - Swarm - Truant ]'),
('Deino','Dark','Dragon','[ Hustle ]'),
('Zweilous','Dark','Dragon','[ Hustle ]'),
('Hydreigon','Dark','Dragon','[ Levitate ]'),
('Larvesta','Bug','Fire','[ FlameBody - Swarm ]'),
('Volcarona','Bug','Fire','[ FlameBody - Swarm ]'),
('Cobalion','Steel','Fighting','[ Justified ]'),
('Terrakion','Rock','Fighting','[ Justified ]'),
('Virizion','Grass','Fighting','[ Justified ]'),
('Tornadus','Flying','','[ Defiant - Prankster ]'),
('Thundurus','Electric','Flying','[ Defiant - Prankster ]'),
('Reshiram','Dragon','Fire','[ Turboblaze ]'),
('Zekrom','Dragon','Electric','[ Teravolt ]'),
('Landorus','Ground','Flying','[ SandForce - SheerForce ]'),
('Kyurem','Dragon','Ice','[ Pressure ]'),
('Keldeo','Water','Fighting','[ Justified ]'),
('Meloetta','Normal','Psychic','[ SereneGrace ]'),
('Genesect','Bug','Steel','[ Download ]'),
('Chespin','Grass','','[ Bulletproof - Overgrow ]'),
('Quilladin','Grass','','[ Bulletproof - Overgrow ]'),
('Chesnaught','Grass','Fighting','[ Bulletproof - Overgrow ]'),
('Fennekin','Fire','','[ Blaze - Magician ]'),
('Braixen','Fire','','[ Blaze - Magician ]'),
('Delphox','Fire','Psychic','[ Blaze - Magician ]'),
('Froakie','Water','','[ Protean - Torrent ]'),
('Frogadier','Water','','[ Protean - Torrent ]'),
('Greninja','Water','Dark','[ Protean - Torrent ]'),
('Bunnelby','Normal','','[ CheekPouch - HugePower - Pickup ]'),
('Diggersby','Normal','Ground','[ CheekPouch - HugePower - Pickup ]'),
('Fletchling','Normal','Flying','[ BigPecks - GaleWings ]'),
('Fletchinder','Fire','Flying','[ FlameBody - GaleWings ]'),
('Talonflame','Fire','Flying','[ FlameBody - GaleWings ]'),
('Scatterbug','Bug','','[ FriendGuard - ShieldDust ]'),
('Spewpa','Bug','','[ FriendGuard - ShedSkin ]'),
('Vivillon','Bug','Flying','[ FriendGuard - ShieldDust ]'),
('Litleo','Fire','Normal','[ Moxie - Rivalry - Unnerve ]'),
('Pyroar','Fire','Normal','[ Moxie - Rivalry - Unnerve ]'),
('FlabÃ©bÃ©','Fairy','','[ FlowerVeil - Symbiosis ]'),
('Floette','Fairy','','[ FlowerVeil - Symbiosis ]'),
('Florges','Fairy','','[ FlowerVeil - Symbiosis ]'),
('Skiddo','Grass','','[ GrassPelt - SapSipper ]'),
('Gogoat','Grass','','[ GrassPelt - SapSipper ]'),
('Pancham','Fighting','','[ IronFist - MoldBreaker - Scrappy ]'),
('Pangoro','Fighting','Dark','[ IronFist - MoldBreaker - Scrappy ]'),
('Furfrou','Normal','','[ FurCoat ]'),
('Espurr','Psychic','','[ Infiltrator - KeenEye - OwnTempo ]'),
('Meowstic','Psychic','','[ Infiltrator - KeenEye - Prankster ]'),
('Honedge','Steel','Ghost','[ NoGuard ]'),
('Doublade','Steel','Ghost','[ NoGuard ]'),
('Aegislash Shield Form','Steel','Ghost','[ StanceChange ]'),
('Spritzee','Fairy','','[ AromaVeil - Healer ]'),
('Aromatisse','Fairy','','[ AromaVeil - Healer ]'),
('Swirlix','Fairy','','[ SweetVeil - Unburden ]'),
('Slurpuff','Fairy','','[ SweetVeil - Unburden ]'),
('Inkay','Dark','Psychic','[ Contrary - Infiltrator - SuctionCups ]'),
('Malamar','Dark','Psychic','[ Contrary - Infiltrator - SuctionCups ]'),
('Binacle','Rock','Water','[ Pickpocket - Sniper - ToughClaws ]'),
('Barbaracle','Rock','Water','[ Pickpocket - Sniper - ToughClaws ]'),
('Skrelp','Poison','Water','[ Adaptability - PoisonPoint - PoisonTouch ]'),
('Dragalge','Poison','Dragon','[ Adaptability - PoisonPoint - PoisonTouch ]'),
('Clauncher','Water','','[ MegaLauncher ]'),
('Clawitzer','Water','','[ MegaLauncher ]'),
('Helioptile','Electric','Normal','[ DrySkin - SandVeil - SolarPower ]'),
('Heliolisk','Electric','Normal','[ DrySkin - SandVeil - SolarPower ]'),
('Tyrunt','Rock','Dragon','[ StrongJaw - Sturdy ]'),
('Tyrantrum','Rock','Dragon','[ RockHead - StrongJaw ]'),
('Amaura','Rock','Ice','[ Refrigerate - SnowWarning ]'),
('Aurorus','Rock','Ice','[ Refrigerate - SnowWarning ]'),
('Sylveon','Fairy','','[ CuteCharm - Pixilate ]'),
('Hawlucha','Fighting','Flying','[ Limber - MoldBreaker - Unburden ]'),
('Dedenne','Electric','Fairy','[ CheekPouch - Pickup - Plus ]'),
('Carbink','Rock','Fairy','[ ClearBody - Sturdy ]'),
('Goomy','Dragon','','[ Gooey - Hydration - SapSipper ]'),
('Sliggoo','Dragon','','[ Gooey - Hydration - SapSipper ]'),
('Goodra','Dragon','','[ Gooey - Hydration - SapSipper ]'),
('Klefki','Steel','Fairy','[ Magician - Prankster ]'),
('Phantump','Ghost','Grass','[ Frisk - Harvest - NaturalCure ]'),
('Trevenant','Ghost','Grass','[ Frisk - Harvest - NaturalCure ]'),
('Small Size Pumpkaboo','Ghost','Grass','[ Frisk - Insomnia - Pickup ]'),
('Small Size Gourgeist','Ghost','Grass','[ Frisk - Insomnia - Pickup ]'),
('Bergmite','Ice','','[ IceBody - OwnTempo - Sturdy ]'),
('Avalugg','Ice','','[ IceBody - OwnTempo - Sturdy ]'),
('Noibat','Flying','Dragon','[ Frisk - Infiltrator - Telepathy ]'),
('Noivern','Flying','Dragon','[ Frisk - Infiltrator - Telepathy ]'),
('Xerneas','Fairy','','[ FairyAura ]'),
('Yveltal','Dark','Flying','[ DarkAura ]'),
('Zygarde','Dragon','Ground','[ AuraBreak ]'),
('Mega Diancie','Rock','Fairy','[ MagicBounce ]'),
('Hoopa','Psychic','Ghost','[ Magician ]'),
('Volcanion','Fire','Water','[ WaterAbsorb ]'),
('Rowlet','Grass','Flying','[ LongReach - Overgrow ]'),
('Dartrix','Grass','Flying','[ LongReach - Overgrow ]'),
('Decidueye','Grass','Ghost','[ LongReach - Overgrow ]'),
('Litten','Fire','','[ Blaze - Intimidate ]'),
('Torracat','Fire','','[ Blaze - Intimidate ]'),
('Incineroar','Fire','Dark','[ Blaze - Intimidate ]'),
('Popplio','Water','','[ LiquidVoice - Torrent ]'),
('Brionne','Water','','[ LiquidVoice - Torrent ]'),
('Primarina','Water','Fairy','[ LiquidVoice - Torrent ]'),
('Pikipek','Normal','Flying','[ KeenEye - Pickup - SkillLink ]'),
('Trumbeak','Normal','Flying','[ KeenEye - Pickup - SkillLink ]'),
('Toucannon','Normal','Flying','[ KeenEye - SheerForce - SkillLink ]'),
('Yungoos','Normal','','[ Adaptability - Stakeout - StrongJaw ]'),
('Gumshoos','Normal','','[ Adaptability - Stakeout - StrongJaw ]'),
('Grubbin','Bug','','[ Swarm ]'),
('Charjabug','Bug','Electric','[ Battery ]'),
('Vikavolt','Bug','Electric','[ Levitate ]'),
('Crabrawler','Fighting','','[ AngerPoint - HyperCutter - IronFist ]'),
('Crabominable','Fighting','Ice','[ AngerPoint - HyperCutter - IronFist ]'),
('Oricorio Baile Style','Fire','Flying','[ Dancer ]'),
('Cutiefly','Bug','Fairy','[ HoneyGather - ShieldDust - SweetVeil ]'),
('Ribombee','Bug','Fairy','[ HoneyGather - ShieldDust - SweetVeil ]'),
('Rockruff','Rock','','[ KeenEye - Steadfast - VitalSpirit ]'),
('Lycanroc','Rock','','[ KeenEye - SandRush - Steadfast ]'),
('Wishiwashi','Water','','[ Schooling ]'),
('Mareanie','Poison','Water','[ Limber - Merciless - Regenerator ]'),
('Toxapex','Poison','Water','[ Limber - Merciless - Regenerator ]'),
('Mudbray','Ground','','[ InnerFocus - OwnTempo - Stamina ]'),
('Mudsdale','Ground','','[ InnerFocus - OwnTempo - Stamina ]'),
('Dewpider','Water','Bug','[ WaterAbsorb - WaterBubble ]'),
('Araquanid','Water','Bug','[ WaterAbsorb - WaterBubble ]'),
('Fomantis','Grass','','[ Contrary - LeafGuard ]'),
('Lurantis','Grass','','[ Contrary - LeafGuard ]'),
('Morelull','Grass','Fairy','[ EffectSpore - Illuminate - RainDish ]'),
('Shiinotic','Grass','Fairy','[ EffectSpore - Illuminate - RainDish ]'),
('Salandit','Poison','Fire','[ Corrosion - Oblivious ]'),
('Salazzle','Poison','Fire','[ Corrosion - Oblivious ]'),
('Stufful','Normal','Fighting','[ CuteCharm - Fluffy - Klutz ]'),
('Bewear','Normal','Fighting','[ Fluffy - Klutz - Unnerve ]'),
('Bounsweet','Grass','','[ LeafGuard - Oblivious - SweetVeil ]'),
('Steenee','Grass','','[ LeafGuard - Oblivious - SweetVeil ]'),
('Tsareena','Grass','','[ LeafGuard - QueenlyMajesty - SweetVeil ]'),
('Comfey','Fairy','','[ FlowerVeil - NaturalCure - Triage ]'),
('Oranguru','Normal','Psychic','[ InnerFocus - Symbiosis - Telepathy ]'),
('Passimian','Fighting','','[ Defiant - Receiver ]'),
('Wimpod','Bug','Water','[ WimpOut ]'),
('Golisopod','Bug','Water','[ EmergencyExit ]'),
('Sandygast','Ghost','Ground','[ SandVeil - WaterCompaction ]'),
('Palossand','Ghost','Ground','[ SandVeil - WaterCompaction ]'),
('Pyukumuku','Water','','[ InnardsOut - Unaware ]'),
('Sin nombre','Normal','','[ BattleArmor ]'),
('Silvally','Normal','','[ RKSSystem ]'),
('Minior Meteor Form','Rock','Flying','[ ShieldsDown ]'),
('Komala','Normal','','[ Comatose ]'),
('Turtonator','Fire','Dragon','[ ShellArmor ]'),
('Togedemaru','Electric','Steel','[ IronBarbs - LightningRod - Sturdy ]'),
('Mimikyu','Ghost','Fairy','[ Disguise ]'),
('Bruxish','Water','Psychic','[ Dazzling - StrongJaw - WonderSkin ]'),
('Drampa','Normal','Dragon','[ Berserk - CloudNine - SapSipper ]'),
('Dhelmise','Ghost','Grass','[ Steelworker ]'),
('Jangmo-o','Dragon','','[ Bulletproof - Overcoat - Soundproof ]'),
('Hakamo-o','Dragon','Fighting','[ Bulletproof - Overcoat - Soundproof ]'),
('Kommo-o','Dragon','Fighting','[ Bulletproof - Overcoat - Soundproof ]'),
('Tapu Koko','Electric','Fairy','[ ElectricSurge - Telepathy ]'),
('Tapu Lele','Psychic','Fairy','[ PsychicSurge - Telepathy ]'),
('Tapu Bulu','Grass','Fairy','[ GrassySurge - Telepathy ]'),
('Tapu Fini','Water','Fairy','[ MistySurge - Telepathy ]'),
('Cosmog','Psychic','','[ Unaware ]'),
('Cosmoem','Psychic','','[ Sturdy ]'),
('Solgaleo','Psychic','Steel','[ FullMetalBody ]'),
('Lunala','Psychic','Ghost','[ ShadowShield ]'),
('Nihilego','Rock','Poison','[ BeastBoost ]'),
('Buzzwole','Bug','Fighting','[ BeastBoost ]'),
('Pheromosa','Bug','Fighting','[ BeastBoost ]'),
('Xurkitree','Electric','','[ BeastBoost ]'),
('Celesteela','Steel','Flying','[ BeastBoost ]'),
('Kartana','Grass','Steel','[ BeastBoost ]'),
('Guzzlord','Dark','Dragon','[ BeastBoost ]'),
('Necrozma','Psychic','','[ PrismArmor ]'),
('Magearna','Steel','Fairy','[ Soul-Heart ]'),
('Marshadow','Fighting','Ghost','[ Technician ]'),
('Poipole','Poison','','[ BeastBoost ]'),
('Naganadel','Poison','Dragon','[ BeastBoost ]'),
('Stakataka','Rock','Steel','[ BeastBoost ]'),
('Blacephalon','Fire','Ghost','[ BeastBoost ]'),
('Zeraora','Electric','','[ VoltAbsorb ]'),
('Meltan','Steel','','[ MagnetPull ]'),
('Melmetal','Steel','','[ IronFist ]'),
('Grookey','Grass','','[ GrassySurge - Overgrow ]'),
('Thwackey','Grass','','[ GrassySurge - Overgrow ]'),
('Rillaboom','Grass','','[ GrassySurge - Overgrow ]'),
('Scorbunny','Fire','','[ Blaze - Libero ]'),
('Raboot','Fire','','[ Blaze - Libero ]'),
('Cinderace','Fire','','[ Blaze - Libero ]'),
('Sobble','Water','','[ Sniper - Torrent ]'),
('Drizzile','Water','','[ Sniper - Torrent ]'),
('Inteleon','Water','','[ Sniper - Torrent ]'),
('Skwovet','Normal','','[ CheekPouch - Gluttony ]'),
('Greedent','Normal','','[ CheekPouch - Gluttony ]'),
('Rookidee','Flying','','[ BigPecks - KeenEye - Unnerve ]'),
('Corvisquire','Flying','','[ BigPecks - KeenEye - Unnerve ]'),
('Corviknight','Flying','Steel','[ MirrorArmor - Pressure - Unnerve ]'),
('Blipbug','Bug','','[ Swarm - Telepathy ]'),
('Dottler','Bug','Psychic','[ Swarm - Telepathy ]'),
('Orbeetle','Bug','Psychic','[ Frisk - Swarm - Telepathy ]'),
('Nickit','Dark','','[ RunAway - Stakeout - Unburden ]'),
('Thievul','Dark','','[ RunAway - Stakeout - Unburden ]'),
('Gossifleur','Grass','','[ CottonDown - EffectSpore - Regenerator ]'),
('Eldegoss','Grass','','[ CottonDown - EffectSpore - Regenerator ]'),
('Wooloo','Normal','','[ Bulletproof - Fluffy - RunAway ]'),
('Dubwool','Normal','','[ Bulletproof - Fluffy - Steadfast ]'),
('Chewtle','Water','','[ ShellArmor - StrongJaw - SwiftSwim ]'),
('Drednaw','Water','Rock','[ ShellArmor - StrongJaw - SwiftSwim ]'),
('Yamper','Electric','','[ BallFetch - Rattled ]'),
('Boltund','Electric','','[ Competitive - StrongJaw ]'),
('Rolycoly','Rock','','[ FlashFire - Heatproof - SteamEngine ]'),
('Carkol','Rock','Fire','[ FlameBody - FlashFire - SteamEngine ]'),
('Coalossal','Rock','Fire','[ FlameBody - FlashFire - SteamEngine ]'),
('Applin','Grass','Dragon','[ Bulletproof - Gluttony - Ripen ]'),
('Flapple','Grass','Dragon','[ Gluttony - Hustle - Ripen ]'),
('Appletun','Grass','Dragon','[ Gluttony - Ripen - ThickFat ]'),
('Silicobra','Ground','','[ SandSpit - SandVeil - ShedSkin ]'),
('Sandaconda','Ground','','[ SandSpit - SandVeil - ShedSkin ]'),
('Cramorant','Flying','Water','[ GulpMissile ]'),
('Arrokuda','Water','','[ PropellerTail - SwiftSwim ]'),
('Barraskewda','Water','','[ PropellerTail - SwiftSwim ]'),
('Toxel','Electric','Poison','[ Klutz - Rattled - Static ]'),
('Toxtricity','Electric','Poison','[ Plus - PunkRock - Technician ]'),
('Sizzlipede','Fire','Bug','[ FlameBody - FlashFire - WhiteSmoke ]'),
('Centiskorch','Fire','Bug','[ FlameBody - FlashFire - WhiteSmoke ]'),
('Clobbopus','Fighting','','[ Limber - Technician ]'),
('Grapploct','Fighting','','[ Limber - Technician ]'),
('Sinistea','Ghost','','[ CursedBody - WeakArmor ]'),
('Polteageist','Ghost','','[ CursedBody - WeakArmor ]'),
('Hatenna','Psychic','','[ Anticipation - Healer - MagicBounce ]'),
('Hattrem','Psychic','','[ Anticipation - Healer - MagicBounce ]'),
('Hatterene','Psychic','Fairy','[ Anticipation - Healer - MagicBounce ]'),
('Impidimp','Dark','Fairy','[ Frisk - Pickpocket - Prankster ]'),
('Morgrem','Dark','Fairy','[ Frisk - Pickpocket - Prankster ]'),
('Grimmsnarl','Dark','Fairy','[ Frisk - Pickpocket - Prankster ]'),
('Obstagoon','Dark','Normal','[ Defiant - Guts - Reckless ]'),
('Perrserker','Steel','','[ BattleArmor - SteelySpirit - ToughClaws ]'),
('Cursola','Ghost','','[ PerishBody - WeakArmor ]'),
('Sirfetchd','Fighting','','[ Scrappy - Steadfast ]'),
('Mr. Rime','Ice','Psychic','[ IceBody - ScreenCleaner - TangledFeet ]'),
('Runerigus','Ground','Ghost','[ WanderingSpirit ]'),
('Milcery','Fairy','','[ AromaVeil - SweetVeil ]'),
('Alcremie','Fairy','','[ AromaVeil - SweetVeil ]'),
('Falinks','Fighting','','[ BattleArmor - Defiant ]'),
('Pincurchin','Electric','','[ ElectricSurge - LightningRod ]'),
('Snom','Ice','Bug','[ IceScales - ShieldDust ]'),
('Frosmoth','Ice','Bug','[ IceScales - ShieldDust ]'),
('Stonjourner','Rock','','[ PowerSpot ]'),
('Eiscue','Ice','','[ IceFace ]'),
('Indeedee','Psychic','Normal','[ InnerFocus - PsychicSurge - Synchronize ]'),
('Morpeko','Electric','Dark','[ HungerSwitch ]'),
('Cufant','Steel','','[ HeavyMetal - SheerForce ]'),
('Copperajah','Steel','','[ HeavyMetal - SheerForce ]'),
('Dracozolt','Electric','Dragon','[ Hustle - SandRush - VoltAbsorb ]'),
('Arctozolt','Electric','Ice','[ SlushRush - Static - VoltAbsorb ]'),
('Dracovish','Water','Dragon','[ SandRush - StrongJaw - WaterAbsorb ]'),
('Arctovish','Water','Ice','[ IceBody - SlushRush - WaterAbsorb ]'),
('Duraludon','Steel','Dragon','[ HeavyMetal - LightMetal - Stalwart ]'),
('Dreepy','Dragon','Ghost','[ ClearBody - CursedBody - Infiltrator ]'),
('Drakloak','Dragon','Ghost','[ ClearBody - CursedBody - Infiltrator ]'),
('Dragapult','Dragon','Ghost','[ ClearBody - CursedBody - Infiltrator ]'),
('Zacian','Fairy','','[ IntrepidSword ]'),
('Zamazenta','Fighting','','[ DauntlessShield ]'),
('Eternatus','Poison','Dragon','[ Pressure ]'),
('Kubfu','Fighting','','[ InnerFocus ]'),
('Urshifu Rapid Strike Style','Fighting','Water','[ UnseenFist ]'),
('Zarude','Dark','Grass','[ LeafGuard ]'),
('Regieleki','Electric','','[ Transistor ]'),
('Regidrago','Dragon','','[Dragon sMaw]'),
('Glastrier','Ice','','[ ChillingNeigh ]'),
('Spectrier','Ghost','','[ GrimNeigh ]'),
('Calyrex','Psychic','Grass','[ Unnerve ]');



	

